test-PR-2
grechaa82/Heartmade-Candles pull request #19
Opened 2023-11-01 18:32 UTC by grechaa82

2023-11-01 19:45 UTC, pingvin1308 commented on backend/HeartmadeCandles/HeartmadeCandles.API/Contracts/Order/Requests/OrderCandleRequest.cs
> +    public decimal Price { get; set; }
Нельзя передавать цену в post запросе при создании заказа. 
Эта цена влияет на то, сколько заработает система.
Соотвественно будет не прикольно если пользователь сможет набрать 0.

2023-11-01 19:45 UTC, pingvin1308 commented on backend/HeartmadeCandles/HeartmadeCandles.API/Contracts/Order/Requests/OrderDecorRequest.cs
> +    public decimal Price { get; set; }
тоже самое про цену

2023-11-01 19:46 UTC, pingvin1308 commented on backend/HeartmadeCandles/HeartmadeCandles.API/Contracts/Order/Requests/OrderLayerColorRequest.cs
> +    public decimal PricePerGram { get; set; }
тоже самое про цену

2023-11-01 19:46 UTC, pingvin1308 commented on backend/HeartmadeCandles/HeartmadeCandles.API/Contracts/Order/Requests/OrderSmellRequest.cs
> +    public decimal Price { get; set; }
тоже самое про цену

2023-11-01 19:46 UTC, pingvin1308 commented on backend/HeartmadeCandles/HeartmadeCandles.API/Contracts/Order/Requests/OrderWickRequest.cs
> +}
тоже самое про цену

2023-11-01 19:57 UTC, pingvin1308 commented on backend/HeartmadeCandles/HeartmadeCandles.Order.DAL/Collections/OrderDetailItemCollection.cs
> +public class OrderDetailItemCollection
OrderDetailItemCollection -> OrderDetailItemDocument

2023-11-01 19:57 UTC, pingvin1308 commented on backend/HeartmadeCandles/HeartmadeCandles.Order.DAL/Collections/SmellCollection.cs
> +public class SmellCollection
Document

2023-11-01 19:57 UTC, pingvin1308 commented on backend/HeartmadeCandles/HeartmadeCandles.Order.DAL/Collections/TypeCandleCollection.cs
> +public class TypeCandleCollection
Document

2023-11-01 19:57 UTC, pingvin1308 commented on backend/HeartmadeCandles/HeartmadeCandles.Order.DAL/Collections/UserCollection.cs
> +{
Document

2023-11-01 19:58 UTC, pingvin1308 commented on backend/HeartmadeCandles/HeartmadeCandles.Order.DAL/Collections/WickCollection.cs
> +public class WickCollection
Document

2023-11-01 20:08 UTC, pingvin1308 requested changes
плоха, не комипилитися, Варнинг. Плоха
NRE везде

2023-11-08 15:40 UTC, grechaa82 commented
Если кратко объяснить измененную логику, то это выглядит следующим образом: перед созданием заказа теперь создается корзина, в которую добавляется сконфигурированная свеча.
После этого свеча извлекается из слоя Constructor и сохраняется в базе данных mongodb. На странице baskets/{basketId} пользователь может просмотреть свой будущий заказ, ввести свои данные и оформить заказ.
Для создания заказа используется объект CreateOrderRequest, затем производится проверка актуальности состояния корзины (изменилась ли цена, можно ли приобрести свечу и прочее), после чего создается заказ.

2023-11-08 19:54 UTC, pingvin1308 commented on backend/HeartmadeCandles/HeartmadeCandles.Order.BL/Services/OrderService.cs
> +            var isComparedConfiguredCandles = basketItem.IsComparedConfiguredCandles(currentStateConfiguredCandle);
Это скорее валидация чем просто проверка состояния

IsComparedConfiguredCandles -> Compare или Validate

2023-11-19 20:12 UTC, pingvin1308 commented on backend/HeartmadeCandles/HeartmadeCandles.API/Contracts/Order/Requests/ConfiguredCandleBasketRequest.cs
> +    public required CandleDetailFilterRequest[] CandleDetailFilterRequests { get; set; }
1) попробовать убрать required.
2) попробовать убрать required и добавить инициализацию значений.
3) попробовать убрать required и добавить конструктор. Но нужно незабыть добавить в конструктор параметры так, чтобы они назывались ровно также как и названия свойств.
4) попробовать добавить конструктор.

2023-11-19 20:12 UTC, pingvin1308 approved these changes

2023-11-21 08:32 UTC, grechaa82 commented on backend/HeartmadeCandles/HeartmadeCandles.API/Contracts/Order/Requests/ConfiguredCandleBasketRequest.cs
> +    public required CandleDetailFilterRequest[] CandleDetailFilterRequests { get; set; }
После удаления JsonPropertyName, все начало работать. Не удалось воспроизвести ошибку, связанную с невозможностью разбора JsonPropertyName.

2023-11-21 08:33 UTC, merged